before:
  hooks:
    - go mod tidy

builds:
  - id: "gidevice-cli"
    main: .
    binary: gidevice

    goos:
      - windows
      - freebsd
      - openbsd
      - linux
      - darwin

    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm64


archives:
  - id: "gidevice-cli"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
